name: ProyectoActions

on: 
  push:
    branches:
      - '*' # Observa cambios en cualquier rama
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print a message
      run: echo "Funciona Actions en cualquier rama"

    - name: Change directory to tienda_deportiva
      run: cd tienda_deportiva

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd tienda_deportiva
        npm install
        
    - name: Run Stylelint
      run: |
        cd tienda_deportiva 
        npx stylelint "**/*.css" || true
        
    - name: Run JavaScript linter
      run: |
        cd tienda_deportiva
        npm run lint:js
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Cambia según tu versión de PHP
        extensions: mbstring

    - name: Install dependencies
      run: |
        cd tienda_deportiva
        composer install

    - name: Run PHPUnit
      run: |
        cd tienda_deportiva
        ./vendor/bin/phpunit
        
        
