name: ProyectoActions

on: 
  push:
    branches:
      - '*' # Observa cambios en cualquier rama
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print a message
      run: echo "Funciona Actions en cualquier rama"

    - name: Change directory to tienda_deportiva
      run: cd tienda_deportiva

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd tienda_deportiva
        npm install

    - name: Run JavaScript linter
      run: |
        cd tienda_deportiva
        npm run lint:js

    - name: Run CSS linter
      run: |
        cd tienda_deportiva
        npm run lint:css
