name: ProyectoActions

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print a message
      run: echo "Funciona Actions en cualquier rama"
